//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("AstroManager")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("Shared public DTOs and contracts used by the AstroManager N.I.N.A. plugin.")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.3.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.3.0+b44b81dce898af389b98db35dda719ef56dbec49")]
[assembly: System.Reflection.AssemblyProductAttribute("AstroManager.Contracts")]
[assembly: System.Reflection.AssemblyTitleAttribute("AstroManager.Contracts")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.3.0")]
[assembly: System.Reflection.AssemblyMetadataAttribute("RepositoryUrl", "https://github.com/Sleeman-IT-Solutions-OG/AstroManager.NinaShared")]

// Von der MSBuild WriteCodeFragment-Klasse generiert.

